# Generated by Django 5.0.3 on 2024-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_desc',
            field=models.CharField(max_length=10000),
        ),
    ]
